# Generated by Django 5.2.7 on 2025-10-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
