# Generated by Django 5.2.7 on 2025-10-29 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_data_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='qty',
        ),
    ]
